name: C/C++ CI v2
on: [push]
env:
  BUILD_TYPE: Release # Release, Debug, RelWithDebInfo, etc.
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2016] #TOfix windows-latest    , macOS-latest] #fails because of SetupHunter - version not present, although first time build succeeded - why ???

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Create Build Environment
      #shell: bash # ON W$ FOR SOME F.REASON using bash in this step causes a failure in configure step
      run: |
       cmake -E make_directory ${{runner.workspace}}/build
       python -m pip install --upgrade pip
       pip3 install wheel setuptools 
       pip3 install conan

    - name: Cache Conan
      uses: actions/cache@v2
      env:
        cache-name: cache-conan-CMake
      with:
        path: ~/.conan/
        key: ${{ matrix.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/CMakeLists.txt') }} #key: ${{ runner.os }}-
        restore-keys: |
          ${{ matrix.os }}-build-${{ env.cache-name }}-
          ${{ matrix.os }}-build-
          ${{ matrix.os }}-

    - name: ninja
      uses: seanmiddleditch/gha-setup-ninja@master

    - name: Configure CMake
      shell: bash # MUST BE BASH TO SUCCEED!!! Use a bash shell so we can use the same syntax for environment variable access regardless of the host operating system
      working-directory: ${{runner.workspace}}/build
      run: cmake -S $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE # -DHUNTER_STATUS_DEBUG=ON # -S -DCMAKE_PROJECT_INCLUDE_BEFORE:STRING=SetupHunter.cmake

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash # the step fails if missing!
      run: cmake --build . --config $BUILD_TYPE # You can specify a specific target with "--target <NAME>"

    - name: Test
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: ctest -C $BUILD_TYPE # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
